title = "SKILLED-LLMS 2026"
baseURL = "https://skilled-llms.github.io/2026/"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "./resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true


[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-GB'
weight = 1
title = "SKILLED-LLMS"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "Matteo Magnini, Nguyen Ha Thanh"
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured  using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
custom_css = ["custom.scss"]

[params.ananke.social.share]
networks = [
  "bluesky"
]

[params.ananke.social.follow]
networks = [
  "bluesky"
]


[params.ananke.social.bluesky]
username = "SKILLED-LLMS.ws"

[markup.goldmark.renderer]
unsafe= true